### ISSUE TITLE
Automatically run script to import meetings from Socrata

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#102]
Acceptance criteria: 
- A script checks for new meetings on a City's feed and imports new meetings when available

Acceptance test:
- Receive a notification that a new meeting has been imported without importing the meeting yourself
- check https://data.austintexas.gov/Government/Austin-City-Council-Agenda-Items/
-- the latest meeting on this link is also the latest meeting in civinomics

**Comment by drew-moore** [comment]
closed via #277ec6d
