### ISSUE TITLE
Comments not showing up on item page

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#115]
I add a comment to this item:
https://civinomics.com/group/id_acc/meeting/id_meeting_511/item/id_item_647

As long as I'm signed in I can see the comment. 
When I log out I can no longer see the comment. 

See attached.
<img width="1279" alt="not_logged_in" src="https://cloud.githubusercontent.com/assets/4564957/25829056/cbed7fe2-3408-11e7-926f-e7619ae815fd.png">
<img width="1277" alt="logged_in" src="https://cloud.githubusercontent.com/assets/4564957/25829055/cbed0364-3408-11e7-84ef-3c2607e4b412.png">

**Comment by drew-moore** [comment]
closed via #89a6bc4

**Comment by drew-moore** [comment]
closed via 89a6bc4
