### ISSUE TITLE
Follow My City

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#18]
As a Citizen,
I want to receive notifications when new meetings or activity occurs for My City,
so that I can participate.

**Comment by rskoenig** [comment]
I suppose from a story perspective they kind of do. From a task perspective they are different.
-#18  just implies the user is added as following in the database
- #47 is the notification function that sends the report to the user

**Comment by rskoenig** [comment]
I'm assuming this story will require the bulk of the notification packages functionality.

**Comment by rskoenig** [comment]
Acceptance criteria:
- A user can sign up to receive notifications when new content is added in a City

Acceptance test 1:
- as a user, navigate to a city that you are not an admin for
- follow the city by clicking a button
- get visual confirmation that you are now following the city
- switch to a different user account
- add a comment to an agenda item in the city
- the original user should receive an email saying that a City he is following has new activity

Acceptance test 2:
- sign in as the first user in test 1
- add a comment to an agenda item in the city you followed in test 1
- you should not receive an email notification because you are the author of the comment

**Comment by drew-moore** [comment]
closed via #9c44ad7
