### ISSUE TITLE
Notify followers when a new Meeting is published

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#46]
As a Follower,
I want to know when a new meeting a City I'm following is published,
so that I can view and participate in it.

**Comment by rskoenig** [comment]
Acceptance criteria:
- Followers are notifies when new meetings are published

Acceptance test 1:
- As an admin, navigate to a meeting that you have privs for
- publish it
- check your email
- you have a notification that a new meeting is published

Acceptance test 2:
- As a non-admin user with an email address that you have access to, follow a City
- Switch to an admin user for the same City
- Publish a new meeting
- Check the email account of the non-admin user, you have a notification that includes a link to the meeting

**Comment by drew-moore** [comment]
closed via #9c44ad7
