### ISSUE TITLE
Notify Followers of new Meeting Report

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#47]
As a Follower,
I want to know when a new Meeting Report is available,
so that I can view it and see what public comment was collected.

**Comment by drew-moore** [comment]
is this a dupe of #18?

**Comment by rskoenig** [comment]
Acceptance criteria: 
-Followers receive an email with the meeting PDF report when the meeting is closed

Acceptance test 1:
- As a user, navigate to a meeting and add a comment
- Follow the meeting (is this the same thing as following the city?)
- As an admin, close the meeting
- The original user and the admin receive an email saying that the meeting is closed with a PDF report attachment
- Find the user's comment in the report

**Comment by drew-moore** [comment]
closed via #9c44ad7
