### ISSUE TITLE
signup modal is bigger than screen

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#90]
<img width="1278" alt="screen shot 2017-04-06 at 9 32 56 am" src="https://cloud.githubusercontent.com/assets/4564957/24765292/26525dd4-1aac-11e7-829f-50c7db4031ed.png">

**Comment by drew-moore** [comment]
closed by #ddcd0e3

**Comment by drew-moore** [comment]
closed by #ddcd0e3
