### ISSUE TITLE
Display loading graphic instead of partial templates on all pages

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#95]
![screen shot 2017-04-19 at 1 42 40 pm](https://cloud.githubusercontent.com/assets/4564957/25201418/84d65374-2506-11e7-8441-8a43dca6daf7.png)

**Comment by rskoenig** [comment]
related to issue #80

**Comment by drew-moore** [comment]
feel free to reopen if there's a reason they're not dupes that I'm missing
